ARG TARGETPLATFORM=linux/arm64

FROM registry1.dso.mil/ironbank/opensource/rustlang/rust:1.95.0 AS builder

RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig build-base

WORKDIR /app
COPY . .
RUN cargo build --release -p usg-tacacs-server

FROM alpine:3.23.4
RUN apk add --no-cache ca-certificates
WORKDIR /app

RUN adduser -D -H -s /sbin/nologin tacacs
USER tacacs

COPY --from=builder /app/target/release/usg-tacacs-server /usr/local/bin/usg-tacacs

EXPOSE 300/tcp 49/tcp
ENTRYPOINT ["/usr/local/bin/usg-tacacs"]
CMD ["--help"]
