// SPDX-License-Identifier: Apache-2.0
//! Configuration structures for audit log forwarding.
//!
//! # NIST SP 800-53 Security Controls
//!
//! Implements CM-6 (Configuration Settings) for audit system configuration.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Syslog protocol for audit forwarding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SyslogProtocol {
    /// TCP
    Tcp,
    /// TCP with TLS (recommended)
    TcpTls,
    /// UDP (unreliable, not recommended for audit logs)
    Udp,
}

/// Syslog facility codes (RFC 5424).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SyslogFacility {
    /// Kernel messages
    Kern,
    /// User-level messages
    User,
    /// Mail system
    Mail,
    /// System daemons
    Daemon,
    /// Security/authorization messages (recommended for TACACS+)
    Auth,
    /// Messages generated by syslogd
    Syslog,
    /// Line printer subsystem
    Lpr,
    /// Network news subsystem
    News,
    /// UUCP subsystem
    Uucp,
    /// Clock daemon
    Cron,
    /// Security/authorization messages (private use)
    Authpriv,
    /// FTP daemon
    Ftp,
    /// NTP subsystem
    Ntp,
    /// Local use 0-7
    Local0,
    Local1,
    Local2,
    Local3,
    Local4,
    Local5,
    Local6,
    Local7,
}

impl SyslogFacility {
    /// Get the RFC 5424 facility code.
    pub fn code(&self) -> u8 {
        match self {
            Self::Kern => 0,
            Self::User => 1,
            Self::Mail => 2,
            Self::Daemon => 3,
            Self::Auth => 4,
            Self::Syslog => 5,
            Self::Lpr => 6,
            Self::News => 7,
            Self::Uucp => 8,
            Self::Cron => 9,
            Self::Authpriv => 10,
            Self::Ftp => 11,
            Self::Ntp => 12,
            Self::Local0 => 16,
            Self::Local1 => 17,
            Self::Local2 => 18,
            Self::Local3 => 19,
            Self::Local4 => 20,
            Self::Local5 => 21,
            Self::Local6 => 22,
            Self::Local7 => 23,
        }
    }
}

/// Syslog configuration.
///
/// # NIST Controls
///
/// | Control | Name | Implementation |
/// |---------|------|----------------|
/// | AU-4 | Audit Log Storage | Forwards audit logs to external syslog server |
/// | AU-9 | Protection of Audit Information | TLS encryption for audit data in transit |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyslogConfig {
    /// Enable syslog forwarding
    pub enabled: bool,

    /// Syslog server hostname or IP
    pub host: String,

    /// Syslog server port (default: 514 for UDP/TCP, 6514 for TLS)
    pub port: u16,

    /// Protocol (tcp, tcp+tls, udp)
    pub protocol: SyslogProtocol,

    /// Syslog facility (default: auth)
    #[serde(default = "default_facility")]
    pub facility: SyslogFacility,

    /// Application name in syslog messages (default: "tacacs-server")
    #[serde(default = "default_app_name")]
    pub app_name: String,

    /// TLS CA certificate for server verification (required for tcp+tls)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls_ca_file: Option<PathBuf>,

    /// TLS client certificate for mTLS (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls_client_cert: Option<PathBuf>,

    /// TLS client private key for mTLS (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls_client_key: Option<PathBuf>,

    /// Connection timeout in seconds (default: 5)
    #[serde(default = "default_timeout")]
    pub timeout_secs: u64,

    /// Reconnect on connection failure
    #[serde(default = "default_reconnect")]
    pub reconnect: bool,

    /// Reconnect interval in seconds (default: 30)
    #[serde(default = "default_reconnect_interval")]
    pub reconnect_interval_secs: u64,
}

fn default_facility() -> SyslogFacility {
    SyslogFacility::Auth
}

fn default_app_name() -> String {
    "tacacs-server".to_string()
}

fn default_timeout() -> u64 {
    5
}

fn default_reconnect() -> bool {
    true
}

fn default_reconnect_interval() -> u64 {
    30
}

/// Elasticsearch configuration.
///
/// # NIST Controls
///
/// | Control | Name | Implementation |
/// |---------|------|----------------|
/// | AU-4 | Audit Log Storage | Forwards audit logs to Elasticsearch for long-term storage |
/// | AU-6 | Audit Review | Enables centralized audit review via Elasticsearch/Kibana |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ElasticsearchConfig {
    /// Enable Elasticsearch forwarding
    pub enabled: bool,

    /// Elasticsearch hosts (e.g., ["https://elk.internal:9200"])
    pub hosts: Vec<String>,

    /// Index pattern (supports strftime, e.g., "tacacs-audit-%Y.%m.%d")
    pub index: String,

    /// API key for authentication (recommended)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,

    /// Username for basic auth (alternative to API key)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,

    /// Password for basic auth (alternative to API key)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// CA certificate file for TLS verification
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ca_cert_file: Option<PathBuf>,

    /// Connection timeout in seconds (default: 30)
    #[serde(default = "default_es_timeout")]
    pub timeout_secs: u64,

    /// Batch size for bulk operations (default: 100)
    #[serde(default = "default_batch_size")]
    pub batch_size: usize,

    /// Flush interval in seconds (default: 10)
    #[serde(default = "default_flush_interval")]
    pub flush_interval_secs: u64,
}

fn default_es_timeout() -> u64 {
    30
}

fn default_batch_size() -> usize {
    100
}

fn default_flush_interval() -> u64 {
    10
}

/// Audit system configuration.
///
/// # NIST Controls
///
/// | Control | Name | Implementation |
/// |---------|------|----------------|
/// | CM-6 | Configuration Settings | Centralized audit configuration with secure defaults |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditConfig {
    /// Syslog forwarding configuration
    #[serde(skip_serializing_if = "Option::is_none")]
    pub syslog: Option<SyslogConfig>,

    /// Elasticsearch forwarding configuration
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elasticsearch: Option<ElasticsearchConfig>,
}

impl AuditConfig {
    /// Check if any audit destination is enabled.
    pub fn is_enabled(&self) -> bool {
        self.syslog.as_ref().map(|s| s.enabled).unwrap_or(false)
            || self.elasticsearch
                .as_ref()
                .map(|e| e.enabled)
                .unwrap_or(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_syslog_facility_codes() {
        assert_eq!(SyslogFacility::Kern.code(), 0);
        assert_eq!(SyslogFacility::Auth.code(), 4);
        assert_eq!(SyslogFacility::Local0.code(), 16);
        assert_eq!(SyslogFacility::Local7.code(), 23);
    }

    #[test]
    fn test_syslog_config_deserialization() {
        let json = r#"{
            "enabled": true,
            "host": "syslog.internal",
            "port": 6514,
            "protocol": "tcptls"
        }"#;

        let config: SyslogConfig = serde_json::from_str(json).unwrap();
        assert!(config.enabled);
        assert_eq!(config.host, "syslog.internal");
        assert_eq!(config.port, 6514);
        assert_eq!(config.protocol, SyslogProtocol::TcpTls);
        assert_eq!(config.facility, SyslogFacility::Auth); // default
        assert_eq!(config.app_name, "tacacs-server"); // default
    }

    #[test]
    fn test_elasticsearch_config_deserialization() {
        let json = r#"{
            "enabled": true,
            "hosts": ["https://elk.internal:9200"],
            "index": "tacacs-audit-%Y.%m.%d",
            "api_key": "base64-encoded-key"
        }"#;

        let config: ElasticsearchConfig = serde_json::from_str(json).unwrap();
        assert!(config.enabled);
        assert_eq!(config.hosts.len(), 1);
        assert_eq!(config.hosts[0], "https://elk.internal:9200");
        assert_eq!(config.index, "tacacs-audit-%Y.%m.%d");
        assert_eq!(config.api_key, Some("base64-encoded-key".to_string()));
        assert_eq!(config.batch_size, 100); // default
    }

    #[test]
    fn test_audit_config_is_enabled() {
        let config_none = AuditConfig {
            syslog: None,
            elasticsearch: None,
        };
        assert!(!config_none.is_enabled());

        let config_syslog = AuditConfig {
            syslog: Some(SyslogConfig {
                enabled: true,
                host: "localhost".to_string(),
                port: 514,
                protocol: SyslogProtocol::Tcp,
                facility: SyslogFacility::Auth,
                app_name: "test".to_string(),
                tls_ca_file: None,
                tls_client_cert: None,
                tls_client_key: None,
                timeout_secs: 5,
                reconnect: true,
                reconnect_interval_secs: 30,
            }),
            elasticsearch: None,
        };
        assert!(config_syslog.is_enabled());

        let config_es = AuditConfig {
            syslog: None,
            elasticsearch: Some(ElasticsearchConfig {
                enabled: true,
                hosts: vec!["http://localhost:9200".to_string()],
                index: "test".to_string(),
                api_key: None,
                username: None,
                password: None,
                ca_cert_file: None,
                timeout_secs: 30,
                batch_size: 100,
                flush_interval_secs: 10,
            }),
        };
        assert!(config_es.is_enabled());
    }
}
