{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    {{- include "usg-tacacs-postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.cluster.name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ .Values.cluster.name }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.tacacsPodLabels | nindent 14 }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: migration
      ports:
        - { protocol: TCP, port: 5432 }
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.operator.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.operator.podLabels | nindent 14 }}
      ports:
        - { protocol: TCP, port: 8000 }
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ .Values.cluster.name }}
      ports:
        - { protocol: TCP, port: 5432 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - to:
        {{- range .Values.networkPolicy.kubernetesApiCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 6443 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.cluster.name }}-migration
  labels:
    {{- include "usg-tacacs-postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: migration
  policyTypes: ["Ingress", "Egress"]
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ .Values.cluster.name }}
      ports:
        - { protocol: TCP, port: 5432 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
{{- end }}
